// <auto-generated />
namespace WebSuiBeauty.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addreview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addreview));
        
        string IMigrationMetadata.Id
        {
            get { return "202307212120310_add-review"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
